MariaDB [openemr]> alter table form_quest_order modify user text;
alter table form_quest_order modify groupname            | varchar(255) | NO   |     | NULL    |                |
alter table form_quest_order modify status               | varchar(16)  | YES  |     | NULL    |                |
alter table form_quest_order modify priority             | varchar(16)  | YES  |     | NULL    |                |
alter table form_quest_order modify pat_first            | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_middle           | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_last             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_ss               | varchar(15)  | YES  |     | NULL    |                |
alter table form_quest_order modify pat_age              | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_sex              | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_email            | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_mobile           | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_phone            | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_street           | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_city             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_state            | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify pat_zip              | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_first            | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_middle           | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_last             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_sex              | varchar(2)   | YES  |     | NULL    |                |
alter table form_quest_order modify ins_ss               | varchar(15)  | YES  |     | NULL    |                |
alter table form_quest_order modify ins_relation         | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_primary          | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_primary_id       | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_primary_plan     | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_primary_policy   | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_primary_group    | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_secondary        | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_secondary_id     | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_secondary_plan   | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_secondary_policy | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_secondary_group  | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_tertiary         | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_tertiary_id      | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_tertiary_plan    | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_tertiary_policy  | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify ins_tertiary_group   | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_first      | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_middle     | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_last       | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_relation   | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_street     | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_city       | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_state      | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_zip        | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_ss         | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify guarantor_phone      | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx0_code             | text         | YES  |     | NULL    |                |
alter table form_quest_order modify dx0_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx1_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx1_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx2_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx2_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx3_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx3_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx4_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx4_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx5_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx5_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx6_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx6_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx7_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx7_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx8_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx8_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx9_code             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify dx9_text             | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify order0_number        | varchar(225) | NO   |     | NULL    |                |
alter table form_quest_order modify order0_type          | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify order0_duration      | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify order0_req_id        | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify order0_abn_id        | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify request_provider     | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify request_facility     | varchar(255) | YES  |     | NULL    |                |
alter table form_quest_order modify request_handling     | varchar(255) | YES  |     | NULL    |                |

